### ISSUE TITLE
TypeDoc + Asciidoc + Antora question

### ISSUE THREAD

**Issue by omfgnuts** [LiskArchive/lisk-legacy-docs#1607]
I am currently extensively research antora+asciidoc, and now I am currently in need to integrate TypeDoc docs. As I can see, you somehow managed to integrate themed htmls or convert results to .adoc.

I was wondering, what's your approach? I tried typedoc --> markdown --> adoc --> antora, but the results are not the best.

Did you manage to create a custom typedoc theme you talked about in issue [#370 ](https://github.com/LiskHQ/lisk-docs/issues/370)or found a better way?

**Comment by omfgnuts** [comment]
cc @Tschakki

**Comment by Tschakki** [comment]
Hey @omfgnuts, thanks for the question!

I was researching this topic myself some time ago, without finding a perfect way of doing it...

Because I couldn’t find a direct way to integrate TypeDoc with Antora, my current approach is a workaround: 
The idea is simply to generate the HTML files with Typedoc directly and adding them to the Antora-generated HTML files, under a specific directory, where they can be referred from.
This obviously has some disadvantages, especially when it comes to linking between the antora-docs and the typedoc-docs, and I only consider it a temporary solution, until I can find more time working on this issue.
Some interesting solutions to check out are mentioned here:

- https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20how.20to.20include.20static.20contents.20beside.20antora.20component
- https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20passthrough.20entire.20html.20file.3F

Another more complicated, but maybe better solution would probably be to create an antora extension, similar to what is discussed here: 

- https://antora.zulipchat.com/#narrow/stream/282400-users/topic/Generating.20content.20from.20source.20code

If you have some other resources to share about this topic, let me know :)

**Comment by omfgnuts** [comment]
Thank you for such a quick and extensive reply, @Tschakki!

I really love what you did with Lisk docs and Antora, it's really an outstanding job!

I will try html-way, but my dev skills are not that good, hope I can find a wat to apply antora css styles to it.

We are also discussing writing some kind of plugin to streamline typedoc --> antora process, but yea, it needs time. Will update you if i figure something out
