### ISSUE TITLE
Improve top nav for mobile view

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#391]
**Describe the bug**
The extended top nav is not using all available space and becomes extremly slim on smaller screens, which looks pretty ugly.

**To Reproduce**
Switch to mobile view and expand the top nav by clicking on the burger icon.

**Comment by belgianwolfie** [comment]
Just to put you on the right way - this is because your #topbar-nav doesnt get a fixed or absolute positioning when going mobile.

See image hereunder for an update in that regard. it's still not all the way there of course, but I hope it puts you on the right track.

```
.navbar-menu.is-active {
     position: fixed;
     right: 0;
}
```

![image](https://user-images.githubusercontent.com/1779759/72746182-c8108f00-3bb1-11ea-94d0-eb25e298db4b.png)
